name: mercave
description: Merca Ve - Aplicación de Compra de Mercado
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.4+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  woocommerce_api: ^0.1.0
  font_awesome_flutter: ^10.3.0
  carousel_slider: ^4.2.1
  sqflite: ^2.2.3
  path_provider: ^2.0.11
  flutter_spinkit: ^5.1.0
  intl: ^0.18.0
  url_launcher: ^6.1.7
  photo_view: ^0.14.0
  badges: ^2.0.3
  flutter_webview_plugin: ^0.4.0
  path: ^1.8.2
  cached_network_image: ^3.2.3
  package_info: ^2.0.2
  share: ^2.0.4
  #firebase_messaging: ^14.2.1
  sign_in_with_apple: ^4.3.0
  #firebase_core: ^2.4.1
  flutter_local_notifications: ^13.0.0
  #cloud_firestore: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
